deployments:
    default:
        port_forwarding:
            80:3000
        environment:
            - HOST_WHITELIST=${SQUASH_DOMAIN}
        build_options: --build-arg HOST_WHITELIST=${SQUASH_DOMAIN}