deployments:
    gothamist:
        port_forwarding:
            80:3000
        environment:
            - HOST_WHITELIST=${SQUASH_DOMAIN}
        build_options: --build-arg HOST_WHITELIST=${SQUASH_DOMAIN} --build-arg CMS_SERVER=${CMS_SERVER}
    depends_on:
      - CMS_SERVER:
          app: cms